### ISSUE TITLE
No output generated in base model check

### ISSUE THREAD

**Issue by matsuobasho** [samlhuillier/code-llama-fine-tune-notebook#1]
Hi Sam, 

Thanks so much for this tutorial.  I'm running your example and for the base model check, the output gets cut off after the context, so I don't see any response generated:

![image](https://github.com/samlhuillier/code-llama-fine-tune-notebook/assets/13874772/d206c139-aeca-4156-9c24-6959fb7b259f)

This shouldn't be relevant but I'm running on Nvidia Tesla T-4 GPU. 
Thanks.

**Comment by samlhuillier** [comment]
Yes that's how it works! Change the max_new_tokens parameter and you'll see a difference :)

**Comment by matsuobasho** [comment]
Thanks, I thought I had increased it earlier with no change but now upped it to 400 and see and output.
