### ISSUE TITLE
output is empty when load fine-tuned model and do evaluation

### ISSUE THREAD

**Issue by i-love-doufunao** [samlhuillier/code-llama-fine-tune-notebook#7]
Hi,I've fine-tuned code llama-7b-hf following your code but it seems fine-tuned model generates empty string till reaching max_output_length with eval_input prompt.My dataset is about Java code and it looks like:

instruction:Implement the method getUserInfo
input: the fields and construction functions of Class that this method is belonged to
output:the method implementation.

Could you share me any ideas how to resolve this issue?

env:
python:3.9
transformers:4.33.1
accelerate:0.20.3
cuda:11.7

**Comment by vietvo89** [comment]
@i-love-doufunao , did you solved the problem? I got the same thing. It seems that `adapter_model.bin` is not saved after training.

**Comment by vietvo89** [comment]
I found the answer from https://github.com/samlhuillier/code-llama-fine-tune-notebook/issues/6#issuecomment-1829249098
